### ISSUE TITLE
Integrate WPC-EMU

### ISSUE THREAD

**Issue by freezy** [vpdb/vpx-js#124]
WPC-EMU is an awesome emulator for WPC ROMs, written in JavaScript.

Let's describe how the web application deals with VPX-JS and how WPC-EMU could fit in.

## Initialization

When a table file is dropped into the browser, two things happen:

1. The UI thread reads the VPX file and creates a three.js scene based on the geometry, textures, materials and lights in the file.
2. A worker thread is spawned. The worker thread also reads the VPX file but ignores the geometry, textures and materials. Instead, it creates a collision tree, instantiates an object for every playfield element, transpiles and executes the table script, and then goes into a loop, where it stays indefinitely.

## Gameplay

The UI thread is pretty dumb. Every frame it posts a message to the worker asking for the changed states since last time. When received, it applies it to the scene and goes on rendering until the next frame. It also sends key presses to the worker.

When the worker thread gets the state request, it has already simulated everything it needs to. So it just diffs the current state against the last sent state, sends it over, and continues its loop. It also receives key presses, which the table script knows how to deal with.

## WPC-EMU

The emu is similar to the physics loop: It has a clock, and on every tick, it simulates the time that has been passed since the last tick.

This fits well into the current situation. The player on the worker thread, which already loops and simulates the physics, would additionally run a cycle on the emulator. Which means executing the `executeCycle()` method of the emu instance.

Note that the worker thread loop doesn't have a fixed-time duration. It essentially runs as fast as it can, since it has the whole thread at its disposal. That means if physics calculations get heavy, the duration will increase.

### The API

Now, the table script uses an ActiveX COM Object to interface with PinMAME. Let's call it the *VPM Controller*. This object is instantiated in the table script, typically at the beginning, and is used to control the playfield and receive user and physics inputs.

So the VPM Controller is the class that would instantiate WPC-EMU and translate its API into PinMAME's. 

There is just one problem: The table script doesn't know about the clock. It just assumes PinMAME does its thing all alone, which is the case for Visual PinMAME, running on its own thread.

There are two solutions for that:

1. We make the player instance a static singleton and let the VPM controller grab it by itself
2. We patch the script to pass the player instance to the controller

I'd vote for 2. So, basically, the VPM controller should look similar to this:

```ts
export class VpmController {

  private emu?: Emu;

  constructor(player: Player) {
    this.initStuff.then(wpcSystem => {
      this.emu = new Emu(wpcSystem);
      player.enableEmuCycle(this.emu);
    });
  }

  public ChangedLamps(): Array<Array<number>> {    
    if (!this.emu) { // might not have been initialized yet
      return [[]];
    }
    const changedLamps = diff(this.emu.getLamps(), this.lastLamps);
    this.lastLamps = this.emu.getLamps();
    return changedLamps;
  }   
  // rest of the API
}
```

Excuse my naive implementation of `ChangedLamps`, that's just to illustrate that all those methods will use the emu instance to do their thing.

**Comment by neophob** [comment]
Make sense. Whats currently crappy is the WPC-Emu's API - which I need to modularise first, so we can reuse this code.

WPC-Emu's API works like this:
`(API - runs in the main thread) - (MARSHALLER) - (EMU - runs in the worker thread)`

About the main loop, today we send a message to the EMU in the worker thread, which will then run this code:

```
    const intervalTimingMs = 1000 / this.desiredFrameRate;
    console.log('resume emu', intervalTimingMs);
    this.intervalId = setInterval(() => {
      this._emuStep();
    }, intervalTimingMs);
```
either I make this dynamic via new call OR we can call emuStep(howManyMsPassed)

**Comment by freezy** [comment]
I think `emuStep(howManyMsPassed)` would be the most appropriate, because the time passed will basically be different for every call.

**Comment by neophob** [comment]
implemented:
- emuStep(howManyMsPassed)
- websocket decoupled - we can use the api for the main thread but there is also an API for within the webworker
- typescript exports implemented for all api's

pending tasks:
- create diff notification (send only changed Lamps, Solenoid, GI, LED)
- option to exclude "expensive state objects" like RAM, VideoRAM
- option to define DMD colors
- write adapter between "VISUAL PINMAME COM OBJECT" and WPC-EMU
- hook it up to vpx-js

**Comment by freezy** [comment]
Here's a test file that currently compiles correctly and integrates VPM into a table. The only thing it currently does is update the playfield inset lamps, which would be the first milestone.

> [mm-playfield.zip](https://github.com/vpdb/vpx-js/files/3800987/mm-playfield.zip)
