### ISSUE TITLE
VPDB.io ROM fetching

### ISSUE THREAD

**Issue by neophob** [vpdb/vpx-js#130]
To get the ROM for a specific VPX table, this is happening:

- GameName property is set (Pinmame game name)
- wpc-emu exposes a function that gives you the VPDB io of this game (if supported)
- fetch ROM list from VPDB.io (https://api.vpdb.io/v1/games/${id}/roms) - where we can find the GameName in the id attribute
- Using the rom_files key we see all the available roms:

```
		"rom_files": [
			{
				"filename": "mm_1_09c.bin",
				"bytes": 1048576,
				"crc": 3655669919,
				"modified_at": "1996-12-25T04:32:00.000Z"
			},
			{
				"filename": "mm_s2.1_0",
				"bytes": 524288,
				"crc": 3311156081,
				"modified_at": "1996-12-25T04:32:00.000Z"
			},
			{
				"filename": "mm_sav3.rom",
				"bytes": 1048576,
				"crc": 3978028400,
				"modified_at": "1996-12-25T04:32:00.000Z"
			},
			{
				"filename": "mm_sav4.rom",
				"bytes": 1048576,
				"crc": 2626284239,
				"modified_at": "1996-12-25T04:32:00.000Z"
			},
			{
				"filename": "mm_sav5.rom",
				"bytes": 1048576,
				"crc": 1158192688,
				"modified_at": "1996-12-25T04:32:00.000Z"
			},
			{
				"filename": "mm_sav6.rom",
				"bytes": 1048576,
				"crc": 1134384626,
				"modified_at": "1996-12-25T04:32:00.000Z"
			}
		],
```

the problem is - we don't have a clue what those files are used for. there is no default extension for the roms. I see two options to resolve this:
- adding a new entry to the game entry that defines the main rom
- the rom_files data structure gets a new "type" attribute: mainRom, soundRom, soundData, state, dump

**Comment by freezy** [comment]
I'd go for setting a type per file. Any idea what types there could be? So far you mentioned:

- `main_rom`
- `sound_rom`
- `sound_data`
- `state_dump`

Anything else?

**Comment by neophob** [comment]
I checked pinmame code, what they define:

```
DCS_SOUNDROM5xm("mm_s2.1_0",  CRC(c55c3b71) SHA1(95febbf16645dd897bdd459ccad9501d2457d1f1), \
                "mm_sav3.rom",CRC(ed1be570) SHA1(ead4c4f89d63ee0b46d8a8bcd8650d506542d1ee), \
                "mm_sav4.rom",CRC(9c89eacf) SHA1(594a2aa81e34658862a9b7f0a83cf514182f2a2d), \
                "mm_sav5.rom",CRC(45089e30) SHA1(e83492109c59e8a2f1ba9e1f793788b97d150a9b), \
                "mm_sav6.rom",CRC(439d55f2) SHA1(d80e7268223157d864674261d140322634fb3bc2))

WPC_ROMSTART(mm,109, "mm_1_09.bin", 0x100000,CRC(9bac4d0c) SHA1(92cbe21802e1a77feff77b78f4dbbdbffb7b14bc)) MM_SOUND WPC_ROMEND
WPC_ROMSTART(mm,109b,"mm_109b.bin",0x100000,CRC(4eaab86a) SHA1(694cbb1154e7374275becfbe4f743fb8d31df8fb)) MM_SOUND WPC_ROMEND
WPC_ROMSTART(mm,109c,"mm_1_09c.bin",0x100000,CRC(d9e5189f) SHA1(fc01855c139d408559605fe9932236250cd566a8)) MM_SOUND WPC_ROMEND
WPC_ROMSTART(mm,10,  "mm_g11.1_0",  0x080000,CRC(6bd735c6) SHA1(3922df00e785610837230d5d9c24b9e082aa6fb6)) MM_SOUND WPC_ROMEND

WPC_ROMSTART(mm,05, "g11-050.rom", 0x080000,CRC(d211ad16) SHA1(539fb0c4ca6fe19ac6140f5792c5b7cd51f737ce))
DCS_SOUNDROM5xm("s2-020.rom",  CRC(ee009ce4) SHA1(36843b2f1a07cf1e23bdff9b7347ceeca7e915bc),
                "mm_sav3.rom",CRC(ed1be570) SHA1(ead4c4f89d63ee0b46d8a8bcd8650d506542d1ee),
                "mm_sav4.rom",CRC(9c89eacf) SHA1(594a2aa81e34658862a9b7f0a83cf514182f2a2d),
                "mm_sav5.rom",CRC(45089e30) SHA1(e83492109c59e8a2f1ba9e1f793788b97d150a9b),
                "mm_sav6.rom",CRC(439d55f2) SHA1(d80e7268223157d864674261d140322634fb3bc2))
WPC_ROMEND
```
to summarize:
- main_rom: the code of the main game rom `mm_1_09c.bin`
- sound_rom: the code to boot the sound board `mm_s2.1_0`
- sound_data: the sound data used by the sound board - `mm_sav?.rom`

I quickly dig deeper if I find another type

**Comment by freezy** [comment]
Alright, thanks. Any way to parse this from PinMAME so I can add it to VPDB?

**Comment by neophob** [comment]
I would argue with a "not feasible" - its a C `#define` struct

see 
https://github.com/mscottford/pinmame/blob/0af03625f6fe2f3af98a58a0914c75266c96f17a/src/wpc/sims/wpc/full/mm.c

as an example. I guess the boring manual way might be the fastest, especially as this data won't change anymore

**Comment by freezy** [comment]
`/WPC_ROMSTART+\s*\(+\s*[^,]+,\s*[^,]+,\s*"([^"]+)/g` should give us all main rom names, no?

**Comment by neophob** [comment]
jep, should. might make sense to get all main roms, agree
