### ISSUE TITLE
Provide initialised RAM / EMU state 

### ISSUE THREAD

**Issue by neophob** [vpdb/vpx-js#135]
If the emulator is initialised, the RAM is not initialised - which results in a special message of the WPC ROM that needs to be confirmed with the ESC key. Today we work around this by:

```
				//TODO HACK - used to launch the rom - if we have a RAM state, this would be obsolete!
				setTimeout(() => {
					logger().info('ESC!');
					emulator.setCabinetInput(16);
				}, 2000);
```
but this is definitive a hack. we should provide a default RAM state that is downloaded and applied to avoid this

**Comment by freezy** [comment]
How does playfield.dev do it?

**Comment by neophob** [comment]
just show all 64 lamps in a matrix, or the manual mapped ( including position) - as optional visual element

**Comment by freezy** [comment]
Well the very first time, do actually don't have a RAM state, so you'd need to trigger it with the switch anyway. Then we can of course store it in `localstorage`.

Why is the timeout needed? After resetting, does the emu need more time before it can accept switch changes?

**Comment by neophob** [comment]
Fixed it more elegant now:

```
				this.emulator.reset();
				// Let the ROM boot, run for 1000ms
				this.emulator.executeCycleForTime(1000, 4);
				// Set initial state for emulator and press ESC to remove the initial
				// message that the RAM was cleared
				this.emulatorCachingService.cacheState(CacheType.CabinetInput, 16);
				this.emulatorCachingService.applyCache(this);
```

**Comment by freezy** [comment]
Ah, nice. Helps with unit testing too!
