### ISSUE TITLE
Store maximal Lamps per ROM (EmulatorState)

### ISSUE THREAD

**Issue by neophob** [vpdb/vpx-js#136]
Today this hack is in place:

```
		for (let n: number = 0; n < newState.length; n++) {
			// HACK: looks like we need the number of lamps per table (here 61)
			if (n < 62 && lastState[n] !== newState[n]) {
				const index = offsetMapperFunction(n);
				result.push([index, newState[n]]);
			}
		}
```
if the ChangedLamp returns more lamps (index > max lamps) then  the VPX implementation chokes - so we need to know how many lamps each rom/game includes and apply this information when fetching nr of ChangedLamps. Probably we also need to know the nr of GI strings and solenoids

**Comment by freezy** [comment]
How does PinMAME do it?

**Comment by neophob** [comment]
afaik PinMame use the core_tLampDisplay 
 struct: https://github.com/mscottford/pinmame/blob/0af03625f6fe2f3af98a58a0914c75266c96f17a/src/wpc/sims/wpc/full/mm.c

using that you know how many lamps exists

**Comment by freezy** [comment]
Hmm, so [this](https://github.com/vpinball/pinmame/blob/master/src/win32com/Controller.cpp) is VPM's `VpmController` implementation.

It looks like [`ChangedLamps`](https://github.com/vpinball/pinmame/blob/master/src/win32com/Controller.cpp#L1259) retrieves the states from [`vp_getChangedLamps`](https://github.com/vpinball/pinmame/blob/master/src/wpc/vpintf.c#L41) which also just seems to loop through the number of max columns.

As far as I understood, your hack prevents the table script from crashing when initializing to 0 at the beginning. But do you actually get any changes for lamps outside of the table script's range later in the game?

**Comment by freezy** [comment]
I've also looked at `core_tLampDisplay`, I think this is only used for PinMAME's own light rendering (some games show the lamp state visually). The only read-usage of that struct is [here](https://github.com/vpinball/pinmame/blob/master/src/wpc/core.c#L1384) and it's for drawing stuff.

Maybe we can get away with not initializing anything and only returning lights the ROM actually changed?

**Comment by neophob** [comment]
> As far as I understood, your hack prevents the table script from crashing when initializing to 0 at the beginning. But do you actually get any changes for lamps outside of the table script's range later in the game?

Nop, the problem is, that I return all 64 lamps - then the VBS part crashes because i return too much lamps (out of index). however eventually I can solve it differently. today this happens:
- current lamps are initialized (Uint8array empty)
- lamp state update
- CURRENT: diff between old (empty) Uint8array and new lamp state - which is obviously all 64 lamps. 
- TO TEST: i could however change the diff part - if the old state is empty / uninitialized then the diff call returns no change and update the old state. this is done the first time, after that I can return only delta values which should only include lamps that actually exists!

**Comment by freezy** [comment]
Yes, that's what I'm proposing: Init all your 64 lamps with 0, and your diff will spit out only lamps that were actually changed by the ROM (i.e. those that actually exist).

**Comment by neophob** [comment]
worked like a charm!
