### ISSUE TITLE
VBS function calls and invalid scope

### ISSUE THREAD

**Issue by neophob** [vpdb/vpx-js#144]
vpm-controller.ts (class) exposes this function:

```
	public Run() {
//whatever
	}
```

when this class is called, `this` is assigned to the function instead to the class. Bcktrace of this call:

```
    at Function.Run (http://localhost:8080/b5e7b3b55421.worker.js:9222:55)
    at VBSHelper.getOrCall (http://localhost:8080/b5e7b3b55421.worker.js:12642:33)
    at TableApi.eval (tablescript.js:17:25)
    at TableApi.emit (http://localhost:8080/b5e7b3b55421.worker.js:101716:5)

    getOrCall(obj, ...params) {
        if (typeof obj === 'function') {
            return obj.bind(obj)(...params); <<
        }
        for (const param of params) {
            obj = obj[param];
        }
        return obj;
    }
```
this is definitive correct for setter and getter calls, not sure if thats the case for all class methods.

Proposal to solve this:

1. fix how we call the functions in the VBS Helper
2. use pure functions in the vpm-controller.ts (no class) - however not sure what other functions VBS Helper is calling

**Comment by freezy** [comment]
Hmm, does removing `.bind()` in the helper keep the scope to `this`?

**Comment by neophob** [comment]
nop, just tried, played around with this but did not have a good solution either atm

**Comment by neophob** [comment]
After reading https://www.freecodecamp.org/news/this-is-why-we-need-to-bind-event-handlers-in-class-components-in-react-f7ea1a6f93eb/ I propose this solution:

for each function which is NOT a get/set function, use this in the constructor:

```
	constructor(player: Player) {
                 ...
		this.Run = this.Run.bind(this);
	}
```
any objections?

**Comment by freezy** [comment]
Can be closed now, right?
