### ISSUE TITLE
Initial switch state (Fliptronics)

### ISSUE THREAD

**Issue by neophob** [vpdb/vpx-js#150]
Today the wpc-system is not initialize the fliptronics or wpc-95 flipper switches. it looks like the visual pinball scripts do not initialize those swiches correctly.

Also WPC-Emu did the switch initialization on it's own.

@freezy do you agree that this needs to be done by the WPC-Emu or is there a section in the VBS script that we don't parse/execute right now?

To reproduce this issue:
- Press the "Coin Door" button to "open" this pinball machine
- Press "Enter" - there you see "R. FLIPPER E.O.S. IS STUCK CLOSED" and "L. FLIPPER E.O.S. IS STUCK CLOSED"

**Comment by freezy** [comment]
It's probably there, since the table we're actually testing is a 70-line version of core.vbs which is 2.3k lines. But to verify!

**Comment by neophob** [comment]
-> defined in WPC.vbs:

```
Const swLRFlip = 112
Const swLLFlip = 114
Const swURFlip = 116
Const swULFlip = 118
```
-> I need to map this to setFliptronicsInput function

**Comment by neophob** [comment]
implemented!
