### ISSUE TITLE
MM Test Table - missing led

### ISSUE THREAD

**Issue by neophob** [vpdb/vpx-js#156]
looks like LED 14 and LED 64 do not light up!

**Comment by freezy** [comment]
The ones currently missing because I've removed them from the script are three lamps that are mapped to an array of lamps:

```vbs
Lights(14)=Array(L14,L14a)
Lights(64)=Array(L64,L64a)
Lights(78)=Array(L78,L78a)
```

Not sure about number four. There is no `l4` light in the MM version we have. Where is it located?

**Comment by neophob** [comment]
update, mixed up test position and led nr. all good then, thanks!
